// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"fmt"
	"net/http"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetCountryNetworksParams is parameters of getCountryNetworks operation.
type GetCountryNetworksParams struct {
	// Список ISO2 кодов стран (уникальные).
	IsoCodes []IsoCode `json:",omitempty"`
}

func unpackGetCountryNetworksParams(packed middleware.Parameters) (params GetCountryNetworksParams) {
	{
		key := middleware.ParameterKey{
			Name: "isoCodes",
			In:   "query",
		}
		params.IsoCodes = packed[key].([]IsoCode)
	}
	return params
}

func decodeGetCountryNetworksParams(args [0]string, argsEscaped bool, r *http.Request) (params GetCountryNetworksParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: isoCodes.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "isoCodes",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				return d.DecodeArray(func(d uri.Decoder) error {
					var paramsDotIsoCodesVal IsoCode
					if err := func() error {
						var paramsDotIsoCodesValVal string
						if err := func() error {
							val, err := d.DecodeValue()
							if err != nil {
								return err
							}

							c, err := conv.ToString(val)
							if err != nil {
								return err
							}

							paramsDotIsoCodesValVal = c
							return nil
						}(); err != nil {
							return err
						}
						paramsDotIsoCodesVal = IsoCode(paramsDotIsoCodesValVal)
						return nil
					}(); err != nil {
						return err
					}
					params.IsoCodes = append(params.IsoCodes, paramsDotIsoCodesVal)
					return nil
				})
			}); err != nil {
				return err
			}
			if err := func() error {
				if params.IsoCodes == nil {
					return errors.New("nil is invalid value")
				}
				if err := (validate.Array{
					MinLength:    0,
					MinLengthSet: false,
					MaxLength:    0,
					MaxLengthSet: false,
				}).ValidateLength(len(params.IsoCodes)); err != nil {
					return errors.Wrap(err, "array")
				}
				if err := validate.UniqueItems(params.IsoCodes); err != nil {
					return errors.Wrap(err, "array")
				}
				var failures []validate.FieldError
				for i, elem := range params.IsoCodes {
					if err := func() error {
						if err := elem.Validate(); err != nil {
							return err
						}
						return nil
					}(); err != nil {
						failures = append(failures, validate.FieldError{
							Name:  fmt.Sprintf("[%d]", i),
							Error: err,
						})
					}
				}
				if len(failures) > 0 {
					return &validate.Error{Fields: failures}
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "isoCodes",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}

// GetCountryNetworksPagedParams is parameters of getCountryNetworksPaged operation.
type GetCountryNetworksPagedParams struct {
	IsoCode IsoCode
	// Номер страницы (0..).
	Page int32
	// Размер страницы.
	Size int32
}

func unpackGetCountryNetworksPagedParams(packed middleware.Parameters) (params GetCountryNetworksPagedParams) {
	{
		key := middleware.ParameterKey{
			Name: "isoCode",
			In:   "query",
		}
		params.IsoCode = packed[key].(IsoCode)
	}
	{
		key := middleware.ParameterKey{
			Name: "page",
			In:   "query",
		}
		params.Page = packed[key].(int32)
	}
	{
		key := middleware.ParameterKey{
			Name: "size",
			In:   "query",
		}
		params.Size = packed[key].(int32)
	}
	return params
}

func decodeGetCountryNetworksPagedParams(args [0]string, argsEscaped bool, r *http.Request) (params GetCountryNetworksPagedParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: isoCode.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "isoCode",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				var paramsDotIsoCodeVal string
				if err := func() error {
					val, err := d.DecodeValue()
					if err != nil {
						return err
					}

					c, err := conv.ToString(val)
					if err != nil {
						return err
					}

					paramsDotIsoCodeVal = c
					return nil
				}(); err != nil {
					return err
				}
				params.IsoCode = IsoCode(paramsDotIsoCodeVal)
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := params.IsoCode.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "isoCode",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: page.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "page",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt32(val)
				if err != nil {
					return err
				}

				params.Page = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           0,
					MaxSet:        false,
					Max:           0,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(params.Page)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "page",
			In:   "query",
			Err:  err,
		}
	}
	// Decode query: size.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "size",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt32(val)
				if err != nil {
					return err
				}

				params.Size = c
				return nil
			}); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           1,
					MaxSet:        true,
					Max:           100000,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(params.Size)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "size",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
