// Code generated by ogen, DO NOT EDIT.
package oas

type GetCountriesRes interface {
	getCountriesRes()
}

type GetCountryNetworksPagedRes interface {
	getCountryNetworksPagedRes()
}

type GetCountryNetworksRes interface {
	getCountryNetworksRes()
}

type GetIpDataRes interface {
	getIpDataRes()
}
