// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	GetCountriesOperation            OperationName = "GetCountries"
	GetCountryNetworksOperation      OperationName = "GetCountryNetworks"
	GetCountryNetworksPagedOperation OperationName = "GetCountryNetworksPaged"
	GetHealthOperation               OperationName = "GetHealth"
	GetIpDataOperation               OperationName = "GetIpData"
)
