// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetCountries implements getCountries operation.
//
// Получение полного перечня кодов стран.
//
// GET /geo/countries
func (UnimplementedHandler) GetCountries(ctx context.Context) (r GetCountriesRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCountryNetworks implements getCountryNetworks operation.
//
// Получение полного перечня подсетей по коду страны.
//
// GET /geo/networks
func (UnimplementedHandler) GetCountryNetworks(ctx context.Context, params GetCountryNetworksParams) (r GetCountryNetworksRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCountryNetworksPaged implements getCountryNetworksPaged operation.
//
// Получение перечня подсетей по коду страны
// постранично.
//
// GET /geo/networks/paged
func (UnimplementedHandler) GetCountryNetworksPaged(ctx context.Context, params GetCountryNetworksPagedParams) (r GetCountryNetworksPagedRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealth implements getHealth operation.
//
// Get service health.
//
// GET /v1/health
func (UnimplementedHandler) GetHealth(ctx context.Context) (r *Health, _ error) {
	return r, ht.ErrNotImplemented
}

// GetIpData implements getIpData operation.
//
// Получение кодов стран по перечню ip адресов.
//
// POST /geo/ip_data
func (UnimplementedHandler) GetIpData(ctx context.Context, req *GeoPayload) (r GetIpDataRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *DefaultErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *DefaultErrorStatusCode) {
	r = new(DefaultErrorStatusCode)
	return r
}
