// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"fmt"
)

func (s *DefaultErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type Cidr string

// Ref: #/components/schemas/CountryRangeData
type CountryRangeData struct {
	Code        IsoCode `json:"code"`
	RangesCount int32   `json:"rangesCount"`
}

// GetCode returns the value of Code.
func (s *CountryRangeData) GetCode() IsoCode {
	return s.Code
}

// GetRangesCount returns the value of RangesCount.
func (s *CountryRangeData) GetRangesCount() int32 {
	return s.RangesCount
}

// SetCode sets the value of Code.
func (s *CountryRangeData) SetCode(val IsoCode) {
	s.Code = val
}

// SetRangesCount sets the value of RangesCount.
func (s *CountryRangeData) SetRangesCount(val int32) {
	s.RangesCount = val
}

// DefaultErrorStatusCode wraps ErrorResponse with StatusCode.
type DefaultErrorStatusCode struct {
	StatusCode int
	Response   ErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *DefaultErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *DefaultErrorStatusCode) GetResponse() ErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *DefaultErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *DefaultErrorStatusCode) SetResponse(val ErrorResponse) {
	s.Response = val
}

// Ref: #/components/schemas/ErrorResponse
type ErrorResponse struct {
	// Result of the request execution (e.g., "ERROR" in case of failure).
	Result string `json:"result"`
	// Response data (null in case of an error).
	Content OptErrorResponseContent `json:"content"`
	Error   ErrorResponseError      `json:"error"`
}

// GetResult returns the value of Result.
func (s *ErrorResponse) GetResult() string {
	return s.Result
}

// GetContent returns the value of Content.
func (s *ErrorResponse) GetContent() OptErrorResponseContent {
	return s.Content
}

// GetError returns the value of Error.
func (s *ErrorResponse) GetError() ErrorResponseError {
	return s.Error
}

// SetResult sets the value of Result.
func (s *ErrorResponse) SetResult(val string) {
	s.Result = val
}

// SetContent sets the value of Content.
func (s *ErrorResponse) SetContent(val OptErrorResponseContent) {
	s.Content = val
}

// SetError sets the value of Error.
func (s *ErrorResponse) SetError(val ErrorResponseError) {
	s.Error = val
}

// Response data (null in case of an error).
type ErrorResponseContent struct{}

type ErrorResponseError struct {
	// Error code.
	Code string `json:"code"`
	// Error description.
	Description string `json:"description"`
}

// GetCode returns the value of Code.
func (s *ErrorResponseError) GetCode() string {
	return s.Code
}

// GetDescription returns the value of Description.
func (s *ErrorResponseError) GetDescription() string {
	return s.Description
}

// SetCode sets the value of Code.
func (s *ErrorResponseError) SetCode(val string) {
	s.Code = val
}

// SetDescription sets the value of Description.
func (s *ErrorResponseError) SetDescription(val string) {
	s.Description = val
}

// Ref: #/components/schemas/GeoIpData
type GeoIpData struct {
	IP   IpAddress `json:"ip"`
	Code IsoCode   `json:"code"`
	// Optional (если появится источник имени страны).
	CountryName OptNilString `json:"countryName"`
}

// GetIP returns the value of IP.
func (s *GeoIpData) GetIP() IpAddress {
	return s.IP
}

// GetCode returns the value of Code.
func (s *GeoIpData) GetCode() IsoCode {
	return s.Code
}

// GetCountryName returns the value of CountryName.
func (s *GeoIpData) GetCountryName() OptNilString {
	return s.CountryName
}

// SetIP sets the value of IP.
func (s *GeoIpData) SetIP(val IpAddress) {
	s.IP = val
}

// SetCode sets the value of Code.
func (s *GeoIpData) SetCode(val IsoCode) {
	s.Code = val
}

// SetCountryName sets the value of CountryName.
func (s *GeoIpData) SetCountryName(val OptNilString) {
	s.CountryName = val
}

// Ref: #/components/schemas/GeoPayload
type GeoPayload struct {
	Ips []IpPayload `json:"ips"`
}

// GetIps returns the value of Ips.
func (s *GeoPayload) GetIps() []IpPayload {
	return s.Ips
}

// SetIps sets the value of Ips.
func (s *GeoPayload) SetIps(val []IpPayload) {
	s.Ips = val
}

type GetCountriesBadRequest ErrorResponse

func (*GetCountriesBadRequest) getCountriesRes() {}

type GetCountriesInternalServerError ErrorResponse

func (*GetCountriesInternalServerError) getCountriesRes() {}

type GetCountriesNotFound ErrorResponse

func (*GetCountriesNotFound) getCountriesRes() {}

type GetCountriesOKApplicationJSON []CountryRangeData

func (*GetCountriesOKApplicationJSON) getCountriesRes() {}

type GetCountryNetworksBadRequest ErrorResponse

func (*GetCountryNetworksBadRequest) getCountryNetworksRes() {}

type GetCountryNetworksInternalServerError ErrorResponse

func (*GetCountryNetworksInternalServerError) getCountryNetworksRes() {}

type GetCountryNetworksNotFound ErrorResponse

func (*GetCountryNetworksNotFound) getCountryNetworksRes() {}

type GetCountryNetworksOKApplicationJSON []IsoCodeNetworks

func (*GetCountryNetworksOKApplicationJSON) getCountryNetworksRes() {}

type GetCountryNetworksPagedBadRequest ErrorResponse

func (*GetCountryNetworksPagedBadRequest) getCountryNetworksPagedRes() {}

type GetCountryNetworksPagedInternalServerError ErrorResponse

func (*GetCountryNetworksPagedInternalServerError) getCountryNetworksPagedRes() {}

type GetCountryNetworksPagedNotFound ErrorResponse

func (*GetCountryNetworksPagedNotFound) getCountryNetworksPagedRes() {}

type GetIpDataBadRequest ErrorResponse

func (*GetIpDataBadRequest) getIpDataRes() {}

type GetIpDataInternalServerError ErrorResponse

func (*GetIpDataInternalServerError) getIpDataRes() {}

type GetIpDataNotFound ErrorResponse

func (*GetIpDataNotFound) getIpDataRes() {}

type GetIpDataOKApplicationJSON []GeoIpData

func (*GetIpDataOKApplicationJSON) getIpDataRes() {}

// Service health status.
// Ref: #/components/schemas/Health
type Health struct {
	// Service uptime (seconds).
	Uptime int `json:"uptime"`
	// Service version.
	Version string `json:"version"`
}

// GetUptime returns the value of Uptime.
func (s *Health) GetUptime() int {
	return s.Uptime
}

// GetVersion returns the value of Version.
func (s *Health) GetVersion() string {
	return s.Version
}

// SetUptime sets the value of Uptime.
func (s *Health) SetUptime(val int) {
	s.Uptime = val
}

// SetVersion sets the value of Version.
func (s *Health) SetVersion(val string) {
	s.Version = val
}

type IpAddress string

// Ref: #/components/schemas/IpPayload
type IpPayload struct {
	IP IpAddress `json:"ip"`
}

// GetIP returns the value of IP.
func (s *IpPayload) GetIP() IpAddress {
	return s.IP
}

// SetIP sets the value of IP.
func (s *IpPayload) SetIP(val IpAddress) {
	s.IP = val
}

type IsoCode string

// Ref: #/components/schemas/IsoCodeNetworks
type IsoCodeNetworks struct {
	Code     IsoCode `json:"code"`
	Networks []Cidr  `json:"networks"`
}

// GetCode returns the value of Code.
func (s *IsoCodeNetworks) GetCode() IsoCode {
	return s.Code
}

// GetNetworks returns the value of Networks.
func (s *IsoCodeNetworks) GetNetworks() []Cidr {
	return s.Networks
}

// SetCode sets the value of Code.
func (s *IsoCodeNetworks) SetCode(val IsoCode) {
	s.Code = val
}

// SetNetworks sets the value of Networks.
func (s *IsoCodeNetworks) SetNetworks(val []Cidr) {
	s.Networks = val
}

// NewOptErrorResponseContent returns new OptErrorResponseContent with value set to v.
func NewOptErrorResponseContent(v *ErrorResponseContent) OptErrorResponseContent {
	return OptErrorResponseContent{
		Value: v,
		Set:   true,
	}
}

// OptErrorResponseContent is optional *ErrorResponseContent.
type OptErrorResponseContent struct {
	Value *ErrorResponseContent
	Set   bool
}

// IsSet returns true if OptErrorResponseContent was set.
func (o OptErrorResponseContent) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptErrorResponseContent) Reset() {
	var v *ErrorResponseContent
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptErrorResponseContent) SetTo(v *ErrorResponseContent) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptErrorResponseContent) Get() (v *ErrorResponseContent, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptErrorResponseContent) Or(d *ErrorResponseContent) *ErrorResponseContent {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PageDataString
type PageDataString struct {
	Content       []Cidr `json:"content"`
	TotalElements int64  `json:"totalElements"`
	TotalPages    int64  `json:"totalPages"`
	Size          int64  `json:"size"`
	Page          int64  `json:"page"`
}

// GetContent returns the value of Content.
func (s *PageDataString) GetContent() []Cidr {
	return s.Content
}

// GetTotalElements returns the value of TotalElements.
func (s *PageDataString) GetTotalElements() int64 {
	return s.TotalElements
}

// GetTotalPages returns the value of TotalPages.
func (s *PageDataString) GetTotalPages() int64 {
	return s.TotalPages
}

// GetSize returns the value of Size.
func (s *PageDataString) GetSize() int64 {
	return s.Size
}

// GetPage returns the value of Page.
func (s *PageDataString) GetPage() int64 {
	return s.Page
}

// SetContent sets the value of Content.
func (s *PageDataString) SetContent(val []Cidr) {
	s.Content = val
}

// SetTotalElements sets the value of TotalElements.
func (s *PageDataString) SetTotalElements(val int64) {
	s.TotalElements = val
}

// SetTotalPages sets the value of TotalPages.
func (s *PageDataString) SetTotalPages(val int64) {
	s.TotalPages = val
}

// SetSize sets the value of Size.
func (s *PageDataString) SetSize(val int64) {
	s.Size = val
}

// SetPage sets the value of Page.
func (s *PageDataString) SetPage(val int64) {
	s.Page = val
}

func (*PageDataString) getCountryNetworksPagedRes() {}
