// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetCountries implements getCountries operation.
	//
	// Получение полного перечня кодов стран.
	//
	// GET /geo/countries
	GetCountries(ctx context.Context) (GetCountriesRes, error)
	// GetCountryNetworks implements getCountryNetworks operation.
	//
	// Получение полного перечня подсетей по коду страны.
	//
	// GET /geo/networks
	GetCountryNetworks(ctx context.Context, params GetCountryNetworksParams) (GetCountryNetworksRes, error)
	// GetCountryNetworksPaged implements getCountryNetworksPaged operation.
	//
	// Получение перечня подсетей по коду страны
	// постранично.
	//
	// GET /geo/networks/paged
	GetCountryNetworksPaged(ctx context.Context, params GetCountryNetworksPagedParams) (GetCountryNetworksPagedRes, error)
	// GetHealth implements getHealth operation.
	//
	// Get service health.
	//
	// GET /v1/health
	GetHealth(ctx context.Context) (*Health, error)
	// GetIpData implements getIpData operation.
	//
	// Получение кодов стран по перечню ip адресов.
	//
	// POST /geo/ip_data
	GetIpData(ctx context.Context, req *GeoPayload) (GetIpDataRes, error)
	// NewError creates *DefaultErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *DefaultErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
